//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\User\source\repos\ConsoleApp2\ConsoleApp2\Test\Robo.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ConsoleApp2.Test {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RoboParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IRoboListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpression([NotNull] RoboParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpression([NotNull] RoboParser.ParenthesizedExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] RoboParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] RoboParser.ConstantExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpression([NotNull] RoboParser.BoolExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpression([NotNull] RoboParser.BoolExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] RoboParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] RoboParser.AdditiveExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpression([NotNull] RoboParser.IdentifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpression([NotNull] RoboParser.IdentifierExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallExpression([NotNull] RoboParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallExpression([NotNull] RoboParser.FunctionCallExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] RoboParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] RoboParser.NotExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>comparisonExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonExpression([NotNull] RoboParser.ComparisonExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>comparisonExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonExpression([NotNull] RoboParser.ComparisonExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] RoboParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] RoboParser.MultiplicativeExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] RoboParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] RoboParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] RoboParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] RoboParser.LineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RoboParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RoboParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] RoboParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] RoboParser.IfBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfBlock([NotNull] RoboParser.ElseIfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfBlock([NotNull] RoboParser.ElseIfBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileBlock([NotNull] RoboParser.WhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileBlock([NotNull] RoboParser.WhileBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] RoboParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] RoboParser.AssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] RoboParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] RoboParser.FunctionCallContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] RoboParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] RoboParser.BlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.identifierOrMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierOrMember([NotNull] RoboParser.IdentifierOrMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.identifierOrMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierOrMember([NotNull] RoboParser.IdentifierOrMemberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] RoboParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] RoboParser.KeywordContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.parent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParent([NotNull] RoboParser.ParentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.parent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParent([NotNull] RoboParser.ParentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember([NotNull] RoboParser.MemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember([NotNull] RoboParser.MemberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] RoboParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] RoboParser.ExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultOp([NotNull] RoboParser.MultOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultOp([NotNull] RoboParser.MultOpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] RoboParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] RoboParser.AddOpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOp([NotNull] RoboParser.BoolOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOp([NotNull] RoboParser.BoolOpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareOp([NotNull] RoboParser.CompareOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareOp([NotNull] RoboParser.CompareOpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="RoboParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] RoboParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RoboParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] RoboParser.ConstantContext context);
}
} // namespace ConsoleApp2.Test
